# -- !Ups

-- To ensure UUIDs are autogenerated
create extension if not exists "uuid-ossp";

-- points in geographic wgs84 coordinates (epsg:4326)
create table stripe_users(
    user_id uuid not null constraint pk_stripe_customers primary key,
    customer_id varchar not null,
    created_at timestamp not null default now(),
    updated_at timestamp not null default now()
);

create table stripe_user_subscriptions(
    id uuid not null constraint pk_stripe_user_subscriptions primary key,
    user_id uuid not null,
    subscription_id varchar not null,
    customer_id varchar not null,
    is_active boolean not null default false,
    valid_until timestamp not null,
    created_at timestamp not null default now(),
    updated_at timestamp not null default now()
);


# -- !Downs