apiVersion: apps/v1
kind: Deployment
metadata:
  name: public-gateway-service
  namespace: public-gateway
  labels:
    app: public-gateway-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: public-gateway-service
  template:
    metadata:
      labels:
        app: public-gateway-service
    spec:
      containers:
        # Sidecar container for cloudsql-proxy to connect to CloudSql database - recommended approach by Google for GKE
        - name: cloudsql-proxy
          image: gcr.io/cloudsql-docker/gce-proxy:1.33.1
          command:
            - /cloud_sql_proxy
            - -instances=fitcentive-dev-03:northamerica-northeast2:gke-dev-env-cloud-sql-instance:=tcp:5432
            - -credential_file=/secrets/cloudsql/credentials.json
          volumeMounts:
            - name: cloudsql-creds
              mountPath: /secrets/cloudsql
              readOnly: true
        - name: public-gateway-service
          image: gcr.io/fitcentive-dev-03/public-gateway:1.0
          imagePullPolicy: Always
          resources:
            requests:
              memory: 300Mi
              cpu: "0.2"
            limits:
              memory: 800Mi
              cpu: "0.8"
          ports:
            - name: http-port
              containerPort: 9000
          readinessProbe:
            httpGet:
              path: /api/gateway/health
              port: 9000
            initialDelaySeconds: 60
            periodSeconds: 30
          livenessProbe:
            httpGet:
              path: /api/gateway/health
              port: 9000
            initialDelaySeconds: 120
            periodSeconds: 15
          envFrom:
            - secretRef:
                name: internal-service-secret
            - secretRef:
                name: image-service-secret
            - secretRef:
                name: public-gateway-service-service-account-credentials
            - secretRef:
                name: admob-ad-unit-ids
            - secretRef:
                name: public-gateway-service-cloudsql-database-credentials
          env:
            - name: GCP_PROJECT_NAME
              value: "fitcentive-dev-03"
            - name: IMAGE_SERVICE_HOST
              value: "http://image-service.image-service"
            - name: IMAGE_SERVICE_PORT
              value: "10260"
            - name: IMAGE_PROXY_HOST
              value: "http://image-proxy.image-proxy"
            - name: IMAGE_PROXY_PORT
              value: "10270"
            - name: JWT_ISSUER
              value: "https://auth.fitcentive.xyz"
            - name: KEYCLOAK_SERVER_URL
              value: "http://keycloak-service-http.keycloak/auth"
            - name: RUNTIME_ENVIRONMENT
              value: "gke-dev-env"
            - name: TOPIC_USER_ENABLE_PREMIUM
              value: "user-enable-premium"
            - name: TOPIC_USER_DISABLE_PREMIUM
              value: "user-disable-premium"
            - name: SUBSCRIPTION_USER_ENABLE_PREMIUM
              value: "user-enable-premium"
            - name: SUBSCRIPTION_USER_DISABLE_PREMIUM
              value: "user-disable-premium"
            - name: STRIPE_API_KEY
              value: "sk_test_51N6ftREGzewRelCEpk4IRNoORELFmUpbFYMa36OcFoMBGbDKERv1IdD45vacoDAkrFOkhBmwTM9LgEybxqT8N5GC00DRJkUwDn"
            - name: STRIPE_BASE_URL
              value: "https://api.stripe.com/v1"
            - name: USER_SERVICE_HOST
              value: "http://user-service.user"
            - name: USER_SERVICE_PORT
              value: "9000"
            - name: SRIPE_PRODUCT_ID
              value: "prod_Nte5eUFCJAQkJv"
            - name: STRIPE_PRODUCT_PRICE_ID
              value: "price_1N7qn1EGzewRelCEYmI1iadM"
            - name: STRIPE_WEBHOOK_SECRET
              value: "whsec_UEXXXVBzYXr90wquBz7FKEARCHwTRImX"
            - name: DB_HOST
              value: "localhost"
            - name: DB_PORT
              value: "5432"
      volumes:
        - name: cloudsql-creds
          secret:
            secretName: public-gateway-service-cloudsql-instance-credentials

